### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by EagleoutIce** [Code-Inspect/flowr#145]
Add separate steps for:

* [x] lint (always)
* [x] test 
  * [x] with different Node, R versions, and operating systems for full 
  * [x] select one for pushes etc.
* [x] build & deploy documentation (only on main)
* [ ] maybe extra: build (for now, no deployment)
