### ISSUE TITLE
Unify/outsource ESLint rules and GH actions so that all repositories can use them

### ISSUE THREAD

**Issue by Ellpeck** [Code-Inspect/flowr#699]
This is especially important for [vscode-flowr](https://github.com/Code-Inspect/vscode-flowr), which currently uses [a copy](https://github.com/Code-Inspect/vscode-flowr/pull/6#discussion_r1512610534) of this repository's eslint rules.

**Comment by Ellpeck** [comment]
See also workflows and git hooks added by https://github.com/Code-Inspect/vscode-flowr/pull/11

**Comment by Ellpeck** [comment]
- [ ] Use npm for eslint rules
- [ ] Move CI actions to their own repository
- [ ] Move modules to their own repositories and publish their own npm packages
- [ ] Make cli, statistics, benchmark etc. into submodules and ensure that people cloning without submodules get notified that they cloned without submodules
- [ ] Move cli, statistics, benchmark submodule folders into a main "" folder (or something)
- [ ] Reintroduce the plugin that allows separating code parts without being allowed to import them again
